name: insta_node_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  audioplayers: ^5.1.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cloudinary_flutter: ^0.9.0
  cloudinary_url_gen: ^0.9.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_keyboard_visibility: ^5.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^15.1.0+1
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  hexcolor: ^3.0.1
  http: ^1.1.0
  image_editor_plus: ^0.2.5
  image_picker: ^1.0.2
  insta_assets_crop: ^0.0.2
  photo_manager: ^3.0.0-dev.2
  photo_manager_image_provider: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  socket_io_client: ^2.0.2
  story_view: ^0.15.0
  url_launcher: ^6.1.14
  video_player: ^2.7.0
  visibility_detector: ^0.4.0+2

dev_dependencies:


  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_logo.png"


flutter:


  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

